/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './panel.component';
const styles_PanelComponent:any[] = ([] as any[]);
export const RenderType_PanelComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PanelComponent,
  data: {}
}
);
export function View_PanelComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),12,'div',[[
        'class',
        'panel panel-default'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n                 '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'panel-heading'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n                   '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h3',[[
        'class',
        'panel-title'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n                 '])),
    (l()(),import0.ɵted((null as any),['\n                 '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'div',[[
        'class',
        'panel-body'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n                      '])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n                 '])),
    (l()(),import0.ɵted((null as any),['\n               ']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.PanelComponent = v.component;
    const currVal_0:any = co.title;
    ck(v,5,0,currVal_0);
  });
}
function View_PanelComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ksf-panel',([] as any[]),(null as any),(null as any),(null as any),View_PanelComponent_0,RenderType_PanelComponent)),
    import0.ɵdid(49152,(null as any),0,import1.PanelComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const PanelComponentNgFactory:import0.ComponentFactory<import1.PanelComponent> = import0.ɵccf('ksf-panel',import1.PanelComponent,View_PanelComponent_Host_0,{title: 'title'},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovR2xvYmFsV2ViT2kvd29ya3NwYWNlL25nMi1rc2Yvc3JjL3BhbmVsL3BhbmVsLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9HbG9iYWxXZWJPaS93b3Jrc3BhY2UvbmcyLWtzZi9zcmMvcGFuZWwvcGFuZWwuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovR2xvYmFsV2ViT2kvd29ya3NwYWNlL25nMi1rc2Yvc3JjL3BhbmVsL3BhbmVsLmNvbXBvbmVudC50cy5QYW5lbENvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovR2xvYmFsV2ViT2kvd29ya3NwYWNlL25nMi1rc2Yvc3JjL3BhbmVsL3BhbmVsLmNvbXBvbmVudC50cy5QYW5lbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJwYW5lbCBwYW5lbC1kZWZhdWx0XCI+XG4gICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJwYW5lbC1oZWFkaW5nXCI+XG4gICAgICAgICAgICAgICAgICAgPGgzIGNsYXNzPVwicGFuZWwtdGl0bGVcIj57e3RpdGxlfX08L2gzPlxuICAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz1cInBhbmVsLWJvZHlcIj5cbiAgICAgICAgICAgICAgICAgICAgICA8bmctY29udGVudD48L25nLWNvbnRlbnQ+XG4gICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgPC9kaXY+IiwiPGtzZi1wYW5lbD48L2tzZi1wYW5lbD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O01DQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFpQztNQUNoQjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQTJCO01BQ3pCO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBd0I7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUFjO0lBQ2xDO01BQ047UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF3QjtnQkFDbkI7SUFBeUI7SUFDeEI7Ozs7SUFKb0I7SUFBQTs7Ozs7SUNGM0M7Z0JBQUE7Ozs7In0=
