/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './form.component';
import * as import2 from '@angular/forms';
const styles_FormComponent:any[] = ([] as any[]);
export const RenderType_FormComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_FormComponent,
  data: {}
}
);
export function View_FormComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n        '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'form',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n            '])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵted((null as any),['    \n    ']))
  ]
  ,(null as any),(null as any));
}
function View_FormComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ksf-form',([] as any[]),(null as any),(null as any),(null as any),View_FormComponent_0,RenderType_FormComponent)),
    import0.ɵdid(49152,(null as any),0,import1.FormComponent,[import2.FormBuilder],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const FormComponentNgFactory:import0.ComponentFactory<import1.FormComponent> = import0.ɵccf('ksf-form',import1.FormComponent,View_FormComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovR2xvYmFsV2ViT2kvd29ya3NwYWNlL25nMi1rc2Yvc3JjL2Zvcm0vZm9ybS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovR2xvYmFsV2ViT2kvd29ya3NwYWNlL25nMi1rc2Yvc3JjL2Zvcm0vZm9ybS5jb21wb25lbnQudHMiLCJuZzovLy9DOi9HbG9iYWxXZWJPaS93b3Jrc3BhY2UvbmcyLWtzZi9zcmMvZm9ybS9mb3JtLmNvbXBvbmVudC50cy5Gb3JtQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9HbG9iYWxXZWJPaS93b3Jrc3BhY2UvbmcyLWtzZi9zcmMvZm9ybS9mb3JtLmNvbXBvbmVudC50cy5Gb3JtQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxmb3JtIGNsYXNzPVwicm93XCI+XG4gICAgICAgICAgICA8bmctY29udGVudD48L25nLWNvbnRlbnQ+XG4gICAgICAgIDwvZm9ybT4gICAgXG4gICAgIiwiPGtzZi1mb3JtPjwva3NmLWZvcm0+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNRO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBa0I7Z0JBQ2Q7SUFBeUI7SUFDdEI7Ozs7OztJQ0hmO2dCQUFBOzs7OyJ9
