/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['th.sorting_ss_asc[_ngcontent-%COMP%] {\r\n    background: url(\'../images/sort_asc.png\') no-repeat center right;\r\n    cursor: pointer;\r\n}\r\n\r\nth.sorting_ss_desc[_ngcontent-%COMP%] {\r\n    background: url(\'../images/sort_desc.png\') no-repeat center right;\r\n    cursor: pointer;\r\n}\r\n\r\nth.sorting_ss[_ngcontent-%COMP%] {\r\n    background: url(\'../images/sort_both.png\') no-repeat center right;\r\n    cursor: pointer;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovR2xvYmFsV2ViT2kvd29ya3NwYWNlL25nMi1rc2Yvc3JjL3RhYmxlL3RhYmxlLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovR2xvYmFsV2ViT2kvd29ya3NwYWNlL25nMi1rc2Yvc3JjL3RhYmxlL3RhYmxlLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
