/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './button.component';
const styles_ButtonComponent:any[] = ([] as any[]);
export const RenderType_ButtonComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ButtonComponent,
  data: {}
}
);
export function View_ButtonComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n                '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'button',([] as any[]),[
      [
        8,
        'className',
        0
      ]
      ,
      [
        8,
        'type',
        0
      ]
      ,
      [
        8,
        'disabled',
        0
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.ButtonComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.executaAcao()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n               ']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.ButtonComponent = v.component;
    const currVal_0:any = import0.ɵinlineInterpolate(1,'btn ',co.estilo,'');
    const currVal_1:any = co.tipo;
    const currVal_2:any = co.desabilitado;
    ck(v,1,0,currVal_0,currVal_1,currVal_2);
    const currVal_3:any = co.nome;
    ck(v,2,0,currVal_3);
  });
}
function View_ButtonComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ksf-button',([] as any[]),(null as any),(null as any),(null as any),View_ButtonComponent_0,RenderType_ButtonComponent)),
    import0.ɵdid(49152,(null as any),0,import1.ButtonComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const ButtonComponentNgFactory:import0.ComponentFactory<import1.ButtonComponent> = import0.ɵccf('ksf-button',import1.ButtonComponent,View_ButtonComponent_Host_0,{
  nome: 'nome',
  estilo: 'estilo',
  tipo: 'tipo',
  desabilitado: 'desabilitado',
  confirmacao: 'confirmacao'
}
,{acao: 'acao'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovR2xvYmFsV2ViT2kvd29ya3NwYWNlL25nMi1rc2Yvc3JjL2J1dHRvbi9idXR0b24uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0dsb2JhbFdlYk9pL3dvcmtzcGFjZS9uZzIta3NmL3NyYy9idXR0b24vYnV0dG9uLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L0dsb2JhbFdlYk9pL3dvcmtzcGFjZS9uZzIta3NmL3NyYy9idXR0b24vYnV0dG9uLmNvbXBvbmVudC50cy5CdXR0b25Db21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L0dsb2JhbFdlYk9pL3dvcmtzcGFjZS9uZzIta3NmL3NyYy9idXR0b24vYnV0dG9uLmNvbXBvbmVudC50cy5CdXR0b25Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgICAgICAgICA8YnV0dG9uIChjbGljayk9XCJleGVjdXRhQWNhbygpXCIgY2xhc3M9XCJidG4ge3tlc3RpbG99fVwiIFt0eXBlXT1cInRpcG9cIiBbZGlzYWJsZWRdPVwiZGVzYWJpbGl0YWRvXCI+e3tub21lfX08L2J1dHRvbj5cbiAgICAgICAgICAgICAgICIsIjxrc2YtYnV0dG9uPjwva3NmLWJ1dHRvbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFDZ0I7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQVE7UUFBQTtRQUFBO01BQUE7TUFBUjtJQUFBO0lBQStGO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFBaUI7Ozs7SUFBaEY7SUFBdUI7SUFBYztJQUFyRSxTQUFnQyxVQUF1QixVQUFjLFNBQXJFO0lBQStGO0lBQUE7Ozs7O0lDRC9HO2dCQUFBOzs7Ozs7Ozs7OzsifQ==
